version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx netlify build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/simplescrum/browser/*

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - node/with-cache:
          steps:
            - run: npx netlify deploy --prod


workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
