version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: 13.14.0
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx netlify build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist/simplescrum/browser/*

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: 13.14.0
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm test

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - node/with-cache:
          steps:
            - run: npx netlify deploy --prod


workflows:
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
