version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:13.14.0-stretch

jobs:

  build:
    executor: default
    steps:
      - checkout
      - run: npm ci
      - run: npx netlify build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist/apps/simplescrum/*

  test:
    executor: default
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run: npx netlify-cli deploy --prod


workflows:
  test-build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
