version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:13.14.0-stretch
    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npx netlify build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist/simplescrum/browser/*

  test:

    docker:
      - image: circleci/node:13.14.0-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:13.14.0-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npx netlify deploy --prod


workflows:
  test-build-deploy:
    jobs:
#      - test
      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
